### ISSUE TITLE
Is the h5 file a pretrained model?

### ISSUE THREAD

**Issue by capmac18** [hemilpatel971/Damage-car-detection#1]
Can you share the scores of the evaluation metrics on the contained datasets?
I tried the model on my own dataset but the accuracy is just 0.52(I haven't checked the distribution of the dataset yet).
I just want to make sure if I will have to train the classifier again.
Thanks.

**Comment by hemilpatel971** [comment]
Hey,
sorry I tried to find the evaluation scores but can not find them. Sorry
about that.

Regards,
Hemil
