### ISSUE TITLE
Dataset Source

### ISSUE THREAD

**Issue by KaisKermani** [hemilpatel971/Damage-car-detection#2]
Is the dataset used images that you collected and labeled yourself?
If not what's the source of the dataset used?

**Comment by hemilpatel971** [comment]
Hi,

No actually I found it on Google. But it's not available anymore, I tried
to find the dataset again was unable to find it. But the labelling I did
was myself. There were around 10k images from that I took a sample and
labelled them.

Regards,
Hemil Patel

**Comment by KaisKermani** [comment]
Dope thanks!
